<?php

namespace App\Http\Controllers\Question;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\Question\QuestionService;
use App\Question;
use App\Answer;
use App\Exceptions\Handler;
use Exception;
use PhpParser\Node\Stmt\TryCatch;
use App\Repositories\AnswerRepository;
use Carbon\Carbon;

class QuestionController extends Controller
{
    protected $questionService;
    protected $answerRepository;

    /*
    *   Contruct service class implementation
    */
    public function __construct(QuestionService $questionService, AnswerRepository $answerRepository){
        $this->middleware('auth');
        $this->questionService = $questionService;
        $this->answerRepository = $answerRepository;
    }

    /**
    *  Create basic CRUD function with question table
    */
    public function create(){
        return view('Admin.pages.create_question');
    }
    public function delete($id){
        $question = Question::find($id);
        $question->delete();
        return redirect()->route('get.question.list');
    }
    public function getQuestionList(){
        $listQuestion = $this->questionService->getQuestionList();
        return view('Admin.pages.question_list', compact('listQuestion'));
    }
    public function getQuestionDetail($id){
        $question = $this->questionService->getQuestionDetail($id);
        $answers = $this->answerRepository->getAnswers($id);
        return view('Admin.pages.question_detail')
            ->with(compact('question', 'answers'));
    }

    /**
    *   Involke new question object, try to get data from $_POST request
    *   If the request is valid, call eloquent save() function to save the question
    *   And then call storeAnswer to save answers of $this.Question
    *   If the answer is insert to table successfully, redirect to question's details
    *   Else, delete $this.Question and redirect to question list with error
    */
    public function store(Request $request){
        try {
            $date =  date('Ymd')+date('Hsi');// Convert dateTime to string with ymdhsi format so it can be sums with subject ID
            $question = new Question();
            $question->id = $request->subject.$request->questionType.$date; //Question ID is generated by sums(question's subject ID and request's dateTime)
            $question->question = $request->question;
            $question->type = $request->questionType;
            $question->subject = $request->subject;
            $question->created_by = $request->user()->name;
            $questionId = $request->subject.$request->questionType.$date;
            $question->save();
            $this->storeAnswer($request, $questionId);
        }catch(\Exception $e){
            $question->delete();
            return redirect()->route('get.question.list')->with('error', 'There are problem with your Question input data, the question has not been added to the database');
        }
        return redirect()->route('home');
    }

    /**
     * For each answer from $_POST's answer[] array, try to involke an Answer objects,
     * Call to function save() to insert the answer to DB
     * If success, continue
     * Else, redirect to question list with error
     *
    */
    public function storeAnswer(Request $request, $questionId){
        try{
            foreach($request->answer as $index=>$ans){
                $answer = new Answer();
                $answer->id = $questionId.$index;
                $answer->question_id = $questionId;
                $answer->answer = $request->answer[$index];
                $answer->created_by = $request->user()->name;
                $answer->updated_by = $request->user()->name;
                $answer->save();
            }
        }catch(\Exception $e){
            return redirect()->route('home')->with('error', 'There are problem with your Answer input data, the question has not been added to the database');
        };
    }

}
